name: Hello World and Get Secrets

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World! This is just a test run"
      - name: "Print Python version"
        run: python --version

  getsecrets:
    runs-on: ubuntu-latest
    needs: hello-world
    steps:
      - name: "Get secrets from GitHub Secrets"
        run: echo "This is the secret value from GitHub Secrets ${{ secrets.SECRETVAL }}"
