name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Build Stage: Print Hello World"
        run: echo "Hello World! This is just a test run"

      - name: "Build Stage: Print Python version"
        run: python --version

  get-secrets:
    runs-on: ubuntu-latest
    needs: build  # This job runs after the 'build' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Get secrets from GitHub Secrets"
        run: echo "This is the secret value from GitHub Secrets ${{ secrets.SECRETVAL }}"
