name: Manual Trigger Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
      version:
        description: 'Version to deploy'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to environment
        run: echo "Deploying to ${{ github.event.inputs.environment }} with version ${{ github.event.inputs.version || 'latest' }}"
